name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest

    steps:
      # Step 1: Set Xcode Version
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      # Step 2: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 3: Debug Repository Structure
      - name: Debug Repository Structure
        run: ls -R

      # Step 4: Change Directory to Xcode Project
      - name: Change Directory to Xcode Project
        run: cd iosApp

      # Step 5: Debug Xcode Project Structure
      - name: Debug Xcode Project Structure
        run: ls -R
        working-directory: iosApp

      # Step 6: Set Default Scheme
      - name: Set Default Scheme
        run: |
          cd iosApp
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo Using default scheme: $default

      # Step 7: Build and Analyze
      - name: Build and Analyze
        env:
          scheme: ${{ 'default' }}
        run: |
          cd iosApp
          if [ $scheme = default ]; then scheme=$(cat default); fi
          file_to_build="iosApp.xcodeproj"
          xcodebuild clean build analyze -scheme "$scheme" -project "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}

      # Step 8: Debug Xcode Version
      - name: Debug Xcode Version
        run: xcodebuild -version

      # Step 9: Check Available Xcode Versions
      - name: Check Available Xcode Versions
        run: ls /Applications | grep Xcode
